### ISSUE TITLE
Clicking anywhere on empty space opens workflow description editor

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#159]
It seems that only clicking on area pointed by green arrow should open workflow description editor.
Currently, it happens on clicking on any empty space (e.g. on areas marked red)
![image](https://user-images.githubusercontent.com/3340954/26843986-4a945aaa-4af2-11e7-91ea-4cc297636c59.png)

**Comment by viktorbenei** [comment]
I believe this is the intended behaviour - what do you think about this @erosdome & @bloodrabbit ?

**Comment by koral--** [comment]
Interesting, even if it is intended what is the reason?

**Comment by erosdome** [comment]
It is intended, clicking on the "background" deselects the currently selected step (if there are any). And when there are no selected steps, the workflow's description is displayed, like in the mentioned case.

**Comment by koral--** [comment]
Understand, I'm not a UX designer but for me it looks a little bit weird behavior.
Moreover clicking on "background" between step blocks or above dashed line has no effect. Is this difference also intended?

**Comment by erosdome** [comment]
Above the dashed line: yes; between the step blocks: no :) It would require a more complex selector, thus a few of these smaller spaces were not included yet. We might add it later though.

**Comment by koral--** [comment]
OK, so I guess that this issue should be kept open until area between step blocks is handled properly.

**Comment by bitrise-adam** [comment]
I'm going to close this as this is intended behaviour

**Comment by koral--** [comment]
@bitrise-adam just for sure, according to 2 posts above: https://github.com/bitrise-io/bitrise-workflow-editor/issues/159#issuecomment-307366118

> Above the dashed line: yes; between the step blocks: no 

So one of two behaviours was not intended at the time of writing that post. Has that intent changed in the meantime or you missed that?

**Comment by bitrise-adam** [comment]
Hi there @koral-- :) yes that intent has changed so now we expect that clicking between the spaces would behave the same as clicking above the dashed line.

**Comment by viktorbenei** [comment]
@koral-- some additional note, to share the reasoning:

- Between the steps: that space can be used for drag-and-drop, that's why it does not de-select the currently selected step. I just tested and it's not perfect, you can't drag-and-drop in the whole area just most of it, but that's a separate issue :P
- The guideline for every other case: if no step is selected the right side should be filled with the workflow's data/info, which today is the stack info & the workflow's description, though this might change in the future (as well as a redesign / UX revision on the workflow editor is also planned ;) )

If you'd have any questions or feedback feel free to ping me on Slack, happy to chat about it :)
