### ISSUE TITLE
Too loose step name validation

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#160]
Empty step name can be accepted. Additionally, when name is empty, its frame is smaller than it should be:
![image](https://user-images.githubusercontent.com/3340954/26844934-545b9d5c-4af5-11e7-84e1-0f50f5cebd65.png)

**Comment by viktorbenei** [comment]
As always, thanks for reporting @koral-- ! ;)

@erosdome In case if the title is empty the original title should be used

**Comment by erosdome** [comment]
I would rather set up a validator which throws away changes if it would mean empty title. For example if title of "Script" has been changed to "My script", then trying to change to empty, the title would be set back to "My script", not "Script"

**Comment by viktorbenei** [comment]
@erosdome I disagree, I believe the CLI handles empty title as not specified. Ask @godrei about this, but the editor should work the same as the CLI

**Comment by koral--** [comment]
>  I believe the CLI handles empty title as not specified
CLI v1.6.1 treats empty and `null` titles as not specified and default title is used.

**Comment by erosdome** [comment]
A new version has been released:

https://discuss.bitrise.io/t/workflow-editor-v1-0-9-released/2004

It now only updates step title if the save button is selected, and it disables that button if field is empty. This is somewhat different from your suggestions, but lines up with the UI's behaviour: if something is specified the same as default, it is not stored in the app's bitrise.yml, otherwise the specified value is used. Let me know what you guys think

**Comment by koral--** [comment]
The main problem seems to be resolved, empty name cannot be accepted using editor.

Visual bug from a screenshot is still present when empty name is specified in `bitrise.yml` but that case seems to be unrealistic, user have to explicitly type empty value.

**Comment by erosdome** [comment]
Added a minor change: in this case, the step's ID will be displayed (only in non-edit mode, in edit mode empty input field will display). Will be available in next release.
