### ISSUE TITLE
Inconsistent workflow name validation

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-workflow-editor#173]
In graphical workflow editor, the workflow name cannot contain spaces and be empty. However, they can be specified (and saved successfully) using bitrise.yml tab.
Such workflow is later properly handled by editor but not always can be triggered, e.g. when name is empty there is an error: `Failed to start Build: trigger pattern did not match any defined mapping`.

So it seems that validation in graphical mode is valid but in bitrise.yml tab is too lenient.

**Comment by viktorbenei** [comment]
Thanks for reporting @koral-- !

The issue here is that technically the CLI allows workflow names with spaces or other special chars in the ID for now. It will print a warning if you e.g. `bitrise run` any workflow or run any validation on the `bitrise.yml`, but technically this is not considered an error just yet, mainly because it wasn't a requirement in the past. We will make this an error in a future CLI version, but for now this is just a warning.

Allowing an empty workflow ID on the other hand is definitely an issue, and should be fixed in the CLI - can you please create a ticket there @koral-- ? If it's fixed there it will be in the editor too, as the editor just sends the yml to the CLI when you edit it in yml mode.

**Comment by viktorbenei** [comment]
Closing as this issue can't be solved in the editor.

**Comment by koral--** [comment]
OK, reported.

**Comment by viktorbenei** [comment]
Thanks! :)
