### ISSUE TITLE
jq: command not found

### ISSUE THREAD

**Issue by frakc** [bitrise-io/bitrise-workflow-editor#403]
In my custom step, I call some jq commands, but in the log, I receive `jq: command not found` 
How to add that dependency? 
Do i need to add brew install jq? Will it install jq each time?

**Comment by frakc** [comment]
well brew also not found
brew: command not found

**Comment by bitce** [comment]
Hi @frakc,

Can you please provide us more insight on the issue you are facing? Are you doing this on the CLI or on the build machines?

You should be able to install anything in a Script step, that you can from a terminal, and since build machines are destroyed with the end of each build, actions need to be re-performed, yes.

**Comment by frakc** [comment]
i just forgot to add qj into yaml dependencies
